### ISSUE TITLE
UBERON:0003902  retinal neural layer, erroneous relationship?

### ISSUE THREAD

**Issue by ANiknejad** [obophenotype/uberon#1318] opened 2017-04-18 18:12 UTC
UBERON:0003902
name: retinal neural layer

relationship: existence_ends_during_or_before MmusDv:0000029 {gci_relation="part_of", gci_filler="NCBITaxon:10090"} ! Theiler stage 22 (mouse)

Sounds to be an error, should be:

relationship: **existence_starts_during_or_after** MmusDv:0000029 {gci_relation="part_of", gci_filler="NCBITaxon:10090"} ! Theiler stage 22 (mouse)

is it correct?

http://www.informatics.jax.org/vocab/gxd/anatomy/EMAPS:1717122

**Comment by cmungall** [comment] 2017-04-18 18:40
The issue is we have 2 equivalence axioms derived from:

```
id: UBERON:0003902 ! retinal neural layer
name: retinal neural layer
...
xref: EMAPA:17171 ! neural retinal epithelium
xref: EMAPA:18590 ! neural retina
```

 * http://purl.obolibrary.org/obo/EMAPA_17171 - neural retinal epithelium - TS18->TS22
 * http://purl.obolibrary.org/obo/EMAPA_18590 - neural retina - TS23->TS28

It's not clear how these two EMAPAs should be linked. They're not linked in EMAPA

**Comment by ANiknejad** [comment] 2017-04-20 07:34
Thanks for explanation, Chris.

I found this information below:

"Cornea, lens and retina could be identified in the eyeball as early as E13. [=TS21] At this time, the retina consisted of a pigmented epithelium layer and a retinal nerve layer or outer retina. Between the pigmented epithelium layer and the retinal nerve layer, there was a narrow space that would be fused at P15. "

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4810997/

While it is not clear why 2 EMAPAs exist, the 'retinal neural layer' sounds to be an embryonic structure that still exists at adult stage, with some positional/morphological differences. So I guess here it is too restrictive to derive the existence relation from one or the other EMAPAs.

EMAPA_17171 is well defined as a part of 'retina epithelium' together with RPE (non-neural pigmented eptihelium), but EMAPA_18590 is just part of some retina

**Comment by ANiknejad** [comment] 2017-04-20 07:56
One explanation for existence of 2 EMAPAs terms could be the 'open/closing eyelid' event starting at TS23, and maybe the 'neural retina' EMAPA_18590 is defined from this event?

http://www.emouseatlas.org/emap/ema/theiler_stages/downloads/theiler2.pdf

**Comment by tfhayamizu** [comment] 2017-04-20 13:26
Sorry for the delay in weighing in on this. There are several factors contributing to the confusion:
(1) the EMAPA file has been updated since the version apparently being used - we should rectify.
(2) the stage range for EMAPA:18590 "neural retina" is TS17-TS28 
(3) EMAPA:17171 "neural retina epithelium" is part-of "neural retina"
note: These changes were made in April of 2016.
(4) there is a currently a rather sharp chronological distinction in the ontology (partly due to legacy factors and open to revision) representing the neural retina as a simple epithelium transitioning to a more complex tissue consisting of many interconnecting layers: 
![screen shot 2017-04-20 at 8 57 17 am](https://cloud.githubusercontent.com/assets/913577/25233004/4f0cf34c-25ab-11e7-95a5-2ec0e83b63b8.png)

**Comment by tfhayamizu** [comment] 2017-04-20 13:30
note: The screen shot above is from a matrix display of expression results in GXD, so you can ignore the colors but should include the boxes with gray circles among the stages included in the ranges for each term.

**Comment by cmungall** [comment] 2017-04-20 17:08
The OBO Library http://obofoundry.org/ontology/emapa.html

is pulling emapa from the JAX ftp site ftp://ftp.hgu.mrc.ac.uk/pub/MouseAtlas/Anatomy/EMAPA.obo
which is from 2014

I'd like to set up a full release pipeline in https://github.com/obophenotype/mouse-anatomy-ontology

but perhaps for now this file
https://github.com/obophenotype/mouse-anatomy-ontology/commits/master/src/ontology/emapa-edit.obo

could be copied to the FTP site?

**Comment by tfhayamizu** [comment] 2017-04-20 17:26
This works for me. I was hesitant to do this while there were other groups concurrently editing the ontology, but this is not the situation at present. The committed file version should be in sync with the version in the "production" database at MGI.

**Comment by gouttegd** [comment] 2021-08-03 10:30
WARNING: This issue has been automatically closed because it has not been updated in more than 3 years. Please re-open it if you still need this to be addressed addressed addressed – we are now getting some resources to deal with such issues.

**Closed by gouttegd** 2021-08-03 10:30 UTC
Labels: autoclosed-unfixed
