### ISSUE TITLE
List of Potential Modeling Issues Identified in Uberon

### ISSUE THREAD

**Issue by ChrisOchs** [obophenotype/uberon#1243] opened 2016-07-18 19:32 UTC
As part of an on-going research project my lab is reviewing several ontologies (e.g., SNOMED, NCIt, GO, others) for modeling issues. We want to thank the Uberon team for the feedback you provided us on the initial list of issues we posted in May (#1218).

After our preliminary review, and based on the feedback we received from the Uberon team, we had a domain expert conduct a more comprehensive review of Uberon. The domain expert identified potential modeling issues among a sample of classes that were chosen according to a criteria we've applied for other ontologies (e.g., the above mentioned ones).

The classes with issues are listed below in alphabetical order. Note that I did not identify these issues but I can forward any feedback/remarks to the domain experts we worked with on this study. These are from the Jan 2016 release.

We appreciate any feedback the Uberon team may have on these issues:

**1st arch mandibular mesenchyme from neural crest**    0010252
Incorrect superclass: The superclass mesenchyme is redundant as it appears to be the superclass of multiple ancestors (redundant for some of the ancestors as well).

Incorrect restriction: The superclass 1st arch mandibular mesenchyme is also the range of the part_of restriction.

**1st arch maxillary mesenchyme from neural crest** 0010253
Same comments as for 1st arch mandibular mesenchyme from neural crest.

**1st arch mesenchyme from neural crest**       0010259
Same comments as for 1st arch mandibular mesenchyme from neural crest in regards to the superclasses mesenchyme and 1st arch mesenchyme as both superclasses and ranges of part of restrictions. 

**2nd arch mesenchyme from head mesenchyme**        0010343
Same comments as for the above classes. The class head mesenchyme from mesoderm is both a superclass and the range of the develops_from restriction.

**2nd arch mesenchyme from neural crest**    0010254
Same comments as for the above classes. As well as the class rhombencephalic neural crest being both a superclass and a range of a part of restriction.

**anterior spinocerebellar tract**  0002987

Incorrect restriction: The part of restriction with a range of medulla oblongata appears to be incorrect. The correct range should be somatosensory system.

Incorrect restriction: The part of restriction with a range of brain appears to be incorrect. It would be more correct to describe it as part of the spinal cord where the tract ends in the cerebellum but not truly part of the cranial part of the CNS. This part_of association does not exist for the spinocerebellar tract concept itself.

**ascending process of clavicle**   4200176

Incorrect superclass: the structure with developmental contribution from neural crest superclass is redundant with the part of restriction.

**axon tract**  0001018

Missing restriction: As with descendants, the tracts are white matter so the part_of that exists in the descendants should exist at this concept (add part of restriction with range of white matter).

**basibranchial 2 tooth**   2001665

Incorrect superclass: The parent mixed ectoderm/mesoderm/endoderm-derived structure seems to be incorrect as there is no endoderm involvement in teeth development.

Missing superclass: There should be a mention of neural crest involvement such as structure with developmental contribution from neural crest

**Brodmann (1909) area 33** 0006476

Missing restriction: Part of restriction with a range of cingulate cortex

**caput epididymis**    0004358

Incorrect superclass: The superclass mesoderm-derived structure is redundant with the develops_from mesoderm

**cloacal epithelium**  0012481

Incorrect superclass: The superclass epithelium is redundant with other superclasses

Incorrect superclass: The superclasses meso-epithelium and endo-epithelium are redundant due to the mixed endoderm/mesoderm-derived structure superclass.

**cuneate fasciculus of spinal cord**   0005835

Incorrect superclass: It is not clear to me the differentiation between and the modeling of tracts and fascicles that are basically the same. In my view the cuneate and the gracile fascicles should be modeled the same but they are not. And here, for cuneate having both tract and fascicle as parents seems redundant.  

**cuneocerebellar tract**   0002640
I'm not sure it is correct to consider the tract as only from the nucleus up to the cerebellum. In many references the cuneocerebellar tract is the whole of the actual spinal tract. Why isn't is modeled the same as the posterior spinocerebellar tract?

**distal tarsal bone pre-cartilage condensation**   0015101

There appear to be missing subclasses. I'm surprised there are no associated descendants such as distal tarsal bone 4 pre-cartilage condensation (this can also be stated as the missing subclasses are missing this class as a superclass).

**embryonic cloacal epithelium**    0009846

Incorrect superclass: Epithelium is redundant

**embryonic tissue**    0005291

Incorrect superclass: From an organizational perspective, tissue is not a structure (although ,in Uberon, Tissue in general is classified as anatomical structure)

**femur endochondral element**  0015052

Incorrect superclass: Limb endochoindral element is theoretically a redundant superclass and should be the superclass of hindlimb endochondral element, but it is not.

**fibula endochondral element** 0015013

Same comment as femur endochondral element.

**forelimb long bone**  0003607

Incorrect superclass: Long bone is a redundant superclass and should be removed.

**gracile fasciculus of spinal cord**   0005826

Missing superclass: To make modeling similar to cuneate, for example, the superclass fasciculus of spinal cord is missing

**hypothenar muscle**   0014377

The three individual muscles involved are not in Uberon and not children of this concept. (Only) Extensor digiti minimi exists.

**lamina V of gray matter of spinal cord**  0016576

Missing part of restriction with range dorsal horn of spinal cord. See 0016577 for similarity.

**lamina VI of gray matter of spinal cord**     0016577

Missing part of restriction with range dorsal horn of spinal cord nucleus proprius of spinal cord. See 0016576 for similarity.

**lamina VII of gray matter of spinal cord**        0016578

Missing part of restriction with range ventral horn of spinal cord. See 0016579 for similarity.

**lamina VIII of gray matter of spinal cord**       0016579

Missing part of restriction with range ventral commissural nucleus of spinal cord.

**lateral lemniscus**   0002953

Missing restrictions: Missing part of restrictions with range brainstem and brainstem white matter.

**lateral plate mesoderm**      0003081

Incorrect superclass: Remove mesoderm derived structure. Lateral plate mesoderm is_a mesoderm and while forming structures it is not a structure.

**lower jaw molar epithelium**  0005654

Incorrect superclass: Dental epithelium is a redandant superclass as there is a superclass molar emithelium

**lumbar spinal cord white matter** 0026386

White matter superclass is redundant and should be removed.

**male mammary gland duct** 0022360

There is no female equivalent class. Alternatively, this class should be removed (in humans there is no male mammary gland duct, but that may be the case in other animals).

**mandibular process mesenchyme from neural crest** 0010336

mesenchyme is a redundant superclass and should be removed.

**mesenchyme of hard palate**   0003424

mesenchyme is a redundant superclass and should be removed.

**minor vestibular gland**  0000461

Incorrect superclass: paraurethral gland. This is actually a synonym and not a broader term.

**muscularis mucosa**   0006676

Incorrect restrictions: remove part_of digestive tract and part_of mucosa and replace with part_of gastrointestinal system mucosa

**olivocerebellar tract**         0002752

Missing restriction: part_of white matter of cerebellum, otherwise there is no relationship to the cerebellum, except by name.

**perianal sebaceous gland**    0012281

Incorrect superclass: Sebacious gland superclass is redundant and should be removed.

**pes joint**   0001487

Incorrect superclass: Skeletal joint superclass is redundant and should be removed

**right lung accessory lobe epithelium**    0005655

Epithelium is a redundant superclass and it should be removed.

**secondary palatal shelf mesenchyme**  0005704

mesenchyme is a redundant superclass and it should be removed.

**spermaceti**  0009755

Missing restriction: produced_by spermaceti organ

Incorrect superclass: organism substance should be replaced with the more specific bodily secretion

**spinal trigeminal tract of medulla**  0002715

Incorrect superclass: spinal trigeminal tract should be removed and the superclass should be the grandparent directly.

Missing restriction: part_of spinal trigeminal tract

**tarsus endochondral element** 0015050

Endochondral element superclass is redundant and should be removed.

**tibialis posterior**  0001667

Missing restriction:  (At least in humans) has_muscle_insertion. The list is not complete as there are many more bones involved with the insertion of the three components of the muscle. Additionally the muscle also has_muscle_origin with the interosseous membrane.

**trigeminal neural crest** 0005563

Incorrect superclass: mesenchyme derived from head neural crest. Also used as range of part_of

**uncinate fasciculus** 0003044

Chosen label/name will be confused with the probably more recognized uncinate fasciculus between the frontal and temporal lobes.

**uncrossed tecto-bulbar tract**    2000296

Missing restriction: part_of cerebellum and possibly medulla as well.

**upper jaw molar odontogenic papilla** 0005700

Incorrect superclass: odontogenic papilla is redundant and should be removed

**urogenital sinus epithelium** 0004902

Epithelium is a redundant superclass and it should be removed

**vagal nerve fiber bundle**    0006116

Missing restriction: part_of vagus nerve

**Comment by cmungall** [comment] 2016-11-15 00:06
There is a lot of diverse issues here, as well as false positives, and repeated instances of a single known issue.

I have attempted to cover many of these but this will be an ongoing effort:

> 1st arch mandibular mesenchyme from neural crest UBERON:0010252
> Incorrect superclass: The superclass mesenchyme is redundant as it appears to be the superclass of multiple ancestors (redundant for some of the ancestors as well)

I don't see this. These are the parents:

```
is_a: UBERON:0009584  ! 1st arch mandibular mesenchyme
is_a: UBERON:0010259  ! 1st arch mesenchyme from neural crest
```


> Incorrect restriction: The superclass 1st arch mandibular mesenchyme is also the range of the part_of restriction.
> 
> 1st arch maxillary mesenchyme from neural crest UBERON:0010253
> Same comments as for 1st arch mandibular mesenchyme from neural crest.
> 
> 1st arch mesenchyme from neural crest UBERON:0010259
> Same comments as for 1st arch mandibular mesenchyme from neural crest in regards to the superclasses mesenchyme and 1st arch mesenchyme as both superclasses and ranges of part of restrictions.
> 
> UBERON:2nd arch mesenchyme from head mesenchyme UBERON:0010343
> Same comments as for the above classes. The class head mesenchyme from mesoderm is both a superclass and the range of the develops_from restriction.
> 
> UBERON:2nd arch mesenchyme from neural crest UBERON:0010254
> Same comments as for the above classes. As well as the class rhombencephalic neural crest being both a superclass and a range of a part of restriction.

All of the above are symptoms of a known issue. See #1291

> anterior spinocerebellar tract UBERON:0002987
> 
> Incorrect restriction: The part of restriction with a range of medulla oblongata appears to be incorrect. The correct range should be somatosensory system.
> 
> Incorrect restriction: The part of restriction with a range of brain appears to be incorrect. It would be more correct to describe it as part of the spinal cord where the tract ends in the cerebellum but not truly part of the cranial part of the CNS. This part_of association does not exist for the spinocerebellar tract concept itself.

TODO

 * FMA regards it part of medulla oblongata
 * MBA as part of cerebellum
 * DHBA as hindbrain

> ascending process of clavicle 4200176
> 
> Incorrect superclass: the structure with developmental contribution from neural crest superclass is redundant with the part of restriction.

Known issue. See #1291

> axon tract UBERON:0001018
> 
> Missing restriction: As with descendants, the tracts are white matter so the part_of that exists in the descendants should exist at this concept (add part of restriction with range of white matter).

This is interesting. Uberon covers all metazoa, and not all axon tracts are white matter, according to the definitions we currently have. We use the term 'axon tract' in a generic way including for example insects, but 'white matter' requires myelinated fibers, and not all lineages with a CNS have myelin or an analog.

However, we should add a phylogenetic GCI here.

> basibranchial UBERON:2 tooth UBERON:2001665
> 
> Incorrect superclass: The parent mixed ectoderm/mesoderm/endoderm-derived structure seems to be incorrect as there is no endoderm involvement in teeth development.

Covered previously, see: #1246

> Missing superclass: There should be a mention of neural crest involvement such as structure with developmental contribution from neural crest

Is this a problem with your visualization? You should see that this is present:

    is_a UBERON:0010314 ! structure with developmental contribution from neural crest
     is_a UBERON:0001091 ! calcareous tooth
      is_a UBERON:2001665 ! basibranchial 2 tooth *** 
 
> Brodmann (1909) area 33 UBERON:0006476
> 
> Missing restriction: Part of restriction with a range of cingulate cortex

Fixed, thanks.

> caput epididymis UBERON:0004358
> 
> Incorrect superclass: The superclass mesoderm-derived structure is redundant with the develops_from mesoderm

See #

> cloacal epithelium UBERON:0012481
> 
> Incorrect superclass: The superclass epithelium is redundant with other superclasses

Note there is no direct epithelium parent:

```
is_a: UBERON:0000077  ! mixed endoderm/mesoderm-derived structure
is_a: UBERON:0003929  ! digestive tract epithelium
is_a: UBERON:0005911  ! endo-epithelium
is_a: UBERON:0012275  ! meso-epithelium
```

> Incorrect superclass: The superclasses meso-epithelium and endo-epithelium are redundant due to the mixed endoderm/mesoderm-derived structure superclass.

Technically these are not redundant.

However, it does point to an issue

> cuneate fasciculus of spinal cord UBERON:0005835
> 
> Incorrect superclass: It is not clear to me the differentiation between and the modeling of tracts and fascicles that are basically the same. In my view the cuneate and the gracile fascicles should be modeled the same but they are not. And here, for cuneate having both tract and fascicle as parents seems redundant.

https://github.com/obophenotype/uberon/issues/286

> cuneocerebellar tract UBERON:0002640
> I'm not sure it is correct to consider the tract as only from the nucleus up to the cerebellum. In many references the cuneocerebellar tract is the whole of the actual spinal tract. Why isn't is modeled the same as the posterior spinocerebellar tract?

TODO - new ticket

> distal tarsal bone pre-cartilage condensation UBERON:0015101
> 
> There appear to be missing subclasses. I'm surprised there are no associated descendants such as distal tarsal bone 4 pre-cartilage condensation (this can also be stated as the missing subclasses are missing this class as a superclass).

Thank you. This can be traced back to UBERON:0015111 'distal tarsal bone 4 endochondral element', which was lacking specific parentage to UBERON:0015099 ! distal tarsal endochondral element. This has been fixed. The reasoner will now give the correct inferences for all members of this design pattern.

> embryonic cloacal epithelium UBERON:0009846
> 
> Incorrect superclass: Epithelium is redundant

No direct parent. This is the parentage:

is_a: UBERON:0000490  ! unilaminar epithelium
is_a: UBERON:0005291  ! embryonic tissue
is_a: UBERON:0009521  ! anal membrane endodermal component
is_a: UBERON:0012481  ! cloacal epithelium


> embryonic tissue UBERON:0005291
> 
> Incorrect superclass: From an organizational perspective, tissue is not a structure (although ,in Uberon, Tissue in general is classified as anatomical structure)

Tissues are structures in uberon. The upper level ontology is CARO:

For a full discussion on these classes, see:

Haendel, M. A., Neuhaus, F., Osumi-Sutherland, D., Mabee, P. M., Mejino, J. L. V. J., Mungall, C. J., & Smith, B. (2007). CARO - The Common Anatomy Reference Ontology. In Anatomy Ontologies for Bioinformatics, Principles and Practice (Vol. Albert Bur). Springer.


> femur endochondral element UBERON:0015052
> 
> Incorrect superclass: Limb endochoindral element is theoretically a redundant superclass and should be the superclass of hindlimb endochondral element, but it is not.

The redundancy was caused by a incorrect logical definition of 'hindlimb endochondral element', this has been fixed.

> fibula endochondral element UBERON:0015013
> 
> Same comment as femur endochondral element.

The reasoner will now infer the correct class

> forelimb long bone UBERON:0003607
> 
> Incorrect superclass: Long bone is a redundant superclass and should be removed.

These are the parents:

```
is_a: UBERON:0003606  ! limb long bone
is_a: UBERON:0008962  ! forelimb bone
```

Neither is redundant. Not all limb long bones are forelimb bones, and not all forelimb bones are long bones

> gracile fasciculus of spinal cord UBERON:0005826
> 
> Missing superclass: To make modeling similar to cuneate, for example, the superclass fasciculus of spinal cord is missing

TODO - should be fixed

> hypothenar muscle UBERON:0014377
> 
> The three individual muscles involved are not in Uberon and not children of this concept. (Only) Extensor digiti minimi exists.

Thank you. These have been added, as well as  palmaris brevis, which FMA considers hypothenar

> lamina V of gray matter of spinal cord UBERON:0016576
> 
> Missing part of restriction with range dorsal horn of spinal cord. See UBERON:0016577 for similarity.

This is present, indirectly via:

UBERON:0016610 ! nucleus proprius of spinal cord

> lamina VI of gray matter of spinal cord UBERON:0016577
> 
> Missing part of restriction with range dorsal horn of spinal cord nucleus proprius of spinal cord. See UBERON:0016576 for similarity.

Link to 'dorsal horn of spinal cord' is present.

The absence of a link to nucleus proprius is deliberate,

TODO - check

> lamina VII of gray matter of spinal cord UBERON:0016578
> 
> Missing part of restriction with range ventral horn of spinal cord. See UBERON:0016579 for similarity.

Fixed, thank you.

> lamina VIII of gray matter of spinal cord UBERON:0016579
> 
> Missing part of restriction with range ventral commissural nucleus of spinal cord.

Fixed, thank you.

> lateral lemniscus UBERON:0002953
> 
> Missing restrictions: Missing part of restrictions with range brainstem and brainstem white matter.

TODO

not clear part of relation is correct, it crosses different regions

> lateral plate mesoderm UBERON:0003081
> 
> Incorrect superclass: Remove mesoderm derived structure. Lateral plate mesoderm is_a mesoderm and while forming structures it is not a structure.

See above for comments on 'anatomical structure'. The CARO definition is very general.

We would not model LPM as being a subclass of mesoderm, as mesoderm is the entire layer (note that ZFA nevertheless models this as subclass)

There are modeling to be made in terms of whether the relationship is part_of or develops_from, or both. We are currently hedging our bets in our current modeling, as we are attempting to be maximally consistent with other sources.

XAO models as both part-of and develops-from. However, I would argue they should remove the develops-from, as the LPM is temporally entirely within the M in their ontology.

EHDAA2 treats the mesoderm as ending at CS13, with structures like LPM continuing afterwards:

     df EHDAA2:0001128 ! mesoderm ***  [ends_at: "CS13"] [starts_at: "CS06b"]
      df EHDAA2:0000736 ! head paraxial mesenchyme [ends_at: "CS14"] [starts_at: "CS09"]
      df EHDAA2:0000871 ! intermediate mesoderm [ends_at: "CS12"] [starts_at: "CS09"]
      df EHDAA2:0000919 ! lateral plate mesoderm [ends_at: "CS13"] [starts_at: "CS09"]
      df EHDAA2:0001113 ! mesenchyme [ends_at: "CS20"] [starts_at: "CS07"]
      df EHDAA2:0001118 ! head mesenchyme from mesoderm and endoderm [ends_at: "CS20"] [starts_at: "CS07"]
      df EHDAA2:0001829 ! septum transversum [ends_at: "CS17"] [starts_at: "CS08"]
      df EHDAA2:0001831 ! septum transversum mesenchyme [ends_at: "CS17"] [starts_at: "CS10"]
      df EHDAA2:0002094 ! trunk and cervical paraxial mesoderm [ends_at: "CS17"] [starts_at: "CS09"]
      df EHDAA2:0002108 ! unsegmented head paraxial mesenchyme [ends_at: "CS10"] [starts_at: "CS09"]
      df EHDAA2:0002109 ! trunk unsegmented mesenchyme [ends_at: "CS10"] [starts_at: "CS09"]
      df EHDAA2:0003241 ! mesoderm blood islands [ends_at: "CS08"] [starts_at: "CS06b"]

Their use of develops_from is thus internally consistent

> lower jaw molar epithelium UBERON:0005654
> 
> Incorrect superclass: Dental epithelium is a redandant superclass as there is a superclass molar emithelium

This is not a direct superclass in uberon. The direct superclasses are:

```
is_a: UBERON:0003236  ! epithelium of lower jaw
is_a: UBERON:0010313  ! neural crest-derived structure
is_a: UBERON:0015839  ! molar epithelium
**is_a: UBERON:0035037  ! jaw epithelium
```

The marked one is redundant. The reasons were to do with a a missing relationship on upper jaw region. This is fixed, so the derived inferences should be fixed.

> lumbar spinal cord white matter UBERON:0026386
> 
> White matter superclass is redundant and should be removed.

there is no direct link to white matter, these are the direct relationships:

```
is_a: UBERON:0002318  ! white matter of spinal cord
relationship: part_of UBERON:0002792 ! lumbar spinal cord
```

neither are redundant

> male mammary gland duct UBERON:0022360
> 
> There is no female equivalent class. Alternatively, this class should be removed (in humans there is no male mammary gland duct, but that may be the case in other animals).

yes, present in adult male Dayak bats (also present in male humans, it just typically regresses)

I'm going to leave this one open for now. 

> mandibular process mesenchyme from neural crest UBERON:0010336
> 
> mesenchyme is a redundant superclass and should be removed.

This is not a direct superclass. The superclasses are:

```
is_a: UBERON:0005253  ! head mesenchyme
is_a: UBERON:0010314  ! structure with developmental contribution from neural crest
```

Assuming this is a problem in display or in using an old version of uberon

> mesenchyme of hard palate UBERON:0003424
> 
> mesenchyme is a redundant superclass and should be removed.

Assuming this is a problem in display or in using an old version of uberon

> minor vestibular gland UBERON:0000461
> 
> Incorrect superclass: paraurethral gland. This is actually a synonym and not a broader term.

TODO

property_value: external_ontology_notes "in MP female urethral gland, Skene gland and paraurethral gland are exact syns. Note that NCITA seems to use the term in a more generic way, as a parent for skene gland, cowper gland (which may be the same as the male bulbo-urethral gland)" xsd:string {external_ontology="MP"}



     is_a NCIT:C12339 ! paraurethral gland *** 
      is_a NCIT:C32395 ! cowper gland
      is_a NCIT:C49311 ! gland of littre
      is_a NCIT:C61122 ! skene gland

TODO


> muscularis mucosa UBERON:0006676
> 
> Incorrect restrictions: remove part_of digestive tract and part_of mucosa and replace with part_of gastrointestinal system mucosa

Replaced mucosa with GI system mucosa.

There is still work to do here. Formally, DT is more specific than GI system. However, I don't believe MM lines as part of the GI system that is not part of the DT?

There is also the issue of this class:

 [UBERON:0006912](http://purl.obolibrary.org/obo/UBERON_0006912) ! urinary bladder muscularis mucosa

TODO: investigate more

> olivocerebellar tract UBERON:0002752
> 
> Missing restriction: part_of white matter of cerebellum, otherwise there is no relationship to the cerebellum, except by name.

MBA and DHBA has it in cerebellar peduncle

FMA and NIFSTD place it in the medulla

TODO:

> perianal sebaceous gland UBERON:0012281
> 
> Incorrect superclass: Sebacious gland superclass is redundant and should be removed.

this isn't a direct superclass

however, it turns out there is a separate redundant superclass

```
is_a: UBERON:0005179  ! pelvic region element
is_a: UBERON:0011252  ! scent gland
is_a: UBERON:0015251  ! modified sebaceous gland
*is_a: UBERON:0016852  ! skin scent gland
relationship: part_of UBERON:0012336 ! perianal skin
```

TODO investigate

> pes joint UBERON:0001487
> 
> Incorrect superclass: Skeletal joint superclass is redundant and should be removed

Assuming this is a problem in display or in using an old version of uberon

> right lung accessory lobe epithelium UBERON:0005655
> 
> Epithelium is a redundant superclass and it should be removed.

Assuming this is a problem in display or in using an old version of uberon

> secondary palatal shelf mesenchyme UBERON:0005704
> 
> mesenchyme is a redundant superclass and it should be removed.

see jaw

> spermaceti UBERON:0009755
> 
> Missing restriction: produced_by spermaceti organ

We don't always assert reciprocals. E.g we have a link between spermaceti organ and spermaceti already. 

TODO

> Incorrect superclass: organism substance should be replaced with the more specific bodily secretion

TODO - glands

> spinal trigeminal tract of medulla UBERON:0002715
> 
> Incorrect superclass: spinal trigeminal tract should be removed and the superclass should be the grandparent directly.
>
> Missing restriction: part_of spinal trigeminal tract

Sorry, not following.

> tarsus endochondral element UBERON:0015050
> 
> Endochondral element superclass is redundant and should be removed.

these are the direct superclasses:

```
is_a: UBERON:0015022  ! hindlimb endochondral element
is_a: UBERON:0015063  ! autopod endochondral element
```

Assuming this is a problem in display or in using an old version of uberon

> tibialis posterior UBERON:0001667
> 
> Missing restriction: (At least in humans) has_muscle_insertion. The list is not complete as there are many more bones involved with the insertion of the three components of the muscle. Additionally the muscle also has_muscle_origin with the interosseous membrane.

TODO
 
> trigeminal neural crest UBERON:0005563
> 
> Incorrect superclass: mesenchyme derived from head neural crest. Also used as range of part_of

not incorrect.

TODO

```
is_a: UBERON:0007213  ! mesenchyme derived from head neural crest
relationship: part_of UBERON:0007213 ! mesenchyme derived from head neural crest
```

> uncinate fasciculus UBERON:0003044
> 
> Chosen label/name will be confused with the probably more recognized uncinate fasciculus between the frontal and temporal lobes.

Excellent catch! In fact UBERON:0003044 will be obsoleted, as it is already conflated, and two new unambiguous concepts will be created.

(FMA and SNOMED refer to cerebral structure; NIFSTD to hidbrain structure)

TODO

> uncrossed tecto-bulbar tract UBERON:2000296
> 
> Missing restriction: part_of cerebellum and possibly medulla as well.

currently part-of medulla via UBERON:0002164 ! tectobulbar tract

> upper jaw molar odontogenic papilla UBERON:0005700
> 
> Incorrect superclass: odontogenic papilla is redundant and should be removed

See above

> urogenital sinus epithelium UBERON:0004902
> Epithelium is a redundant superclass and it should be removed

hmmm

is_a: UBERON:0000483  ! epithelium
is_a: UBERON:0009846  ! embryonic cloacal epithelium


todo

> vagal nerve fiber bundle UBERON:0006116
> 
> Missing restriction: part_of vagus nerve

we would't model it this was, as we model the fiber bundle as being part of the CNS

**Comment by ChrisOchs** [comment] 2016-11-21 17:37
> I don't see this. These are the parents:

Okay, I found an issue with our internal tool that's sometimes displaying the concept in an equivalence as a superclass. Protege also shows it as a subclass (kind of) but its actually an equivalence.

**Comment by cmungall** [comment] 2016-11-21 23:02
Yes, in Protege it's best to view the inferred hierarchy (although there is IMHO no satisfactory hierarchical view that shows a complete existential graph)

In the uberon releases, you only need to look at equivalence axioms if you care about equivalence axioms. The existential graph formed by subClassOf relationships is intended to be complete.

For more on the terminology I'm using, see
https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/

**Comment by gouttegd** [comment] 2021-08-03 10:24
WARNING: This issue has been automatically closed because it has not been updated in more than 3 years. Please re-open it if you still need this to be addressed addressed addressed – we are now getting some resources to deal with such issues.

**Closed by gouttegd** 2021-08-03 10:24 UTC
Labels: autoclosed-unfixed
