### ISSUE TITLE
plant cutin-based cuticle and broaden taxon restrictions of cuticle

### ISSUE THREAD

**Issue by raymond91125** [obophenotype/uberon#2710] opened 2022-11-03 22:25 UTC
**Preferred term label:**
cutin-based cuticle

**Synonyms**

**Definition (free text, please give PubMed ID)**
A cuticular covering that is composed primarily of cutin. Cutin cuticles found in plants function as permeability barriers for water and water-soluble materials. They prevent plant surfaces from becoming wet and also help to prevent plants from drying out.
https://en.wikipedia.org/wiki/Cuticle

**Parent term (use https://www.ebi.ac.uk/ols/ontologies/uberon)**
https://www.ebi.ac.uk/ols/ontologies/uberon/0001002

**Your nano-attribution (ORCID)**

refer to https://github.com/geneontology/go-ontology/issues/24315 cuticle development and children- taxon constraints and plant specific terms

Currently Uberon:0001002 cuticle has a taxon constraint eumatazoa. That seems too restrictive. In wikipedia (where Uberon term def is from), cuticle also includes those found in plants and mushrooms.

**Comment by shawntanzk** [comment] 2022-11-24 10:25
sorry this slipped my radar, think some uberon mail are going to my junk automatically. Will look into this. Thanks

**Comment by shawntanzk** [comment] 2022-12-02 08:07
I think the tricky part is that Uberon is a metazoan ontology. Given the issue is that plants have them too, and the term requested seems more towards plants, perhaps using another ontology would be better. I am also hesitant to remove the taxon restrictions, I assume that in the context of metazoa, the taxon restriction is right. Perhaps instead what we can do is add a comment to the term stating that this term does not apply to plants and mushrooms as Uberon is a metazoan ontology? Thoughts @cmungall?

**Comment by shawntanzk** [comment] 2022-12-08 14:43
@raymond91125 have you found a solution in a plant ontology or something for your request? If so can I close this ticket? Thanks

**Comment by raymond91125** [comment] 2022-12-08 17:43
Yes, that's fine. Thank you!

**Closed** 2022-12-09 08:37 UTC
Labels: new term request
