### ISSUE TITLE
What is a head?

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#379] opened 2013-11-13 01:20 UTC
In ZFA, a head is analagous to a mammalian head+neck.

This causes problems when we bring in spatial disjointness (see issue #378 )

![screen shot 2013-11-12 at 5 11 33 pm](https://f.cloud.github.com/assets/50745/1528003/d833dbc8-4c00-11e3-8bd5-357d8dd1feab.png)

The def of head is pretty vague:

```
def: "The head is the anterior-most division of the body [GO]." [GO:0060322, Wikipedia:Head]
```

What's a division?

We introduced a grouping class to accommodate this:
- [UBERON:0007811](http://purl.obolibrary.org/obo/UBERON_0007811) ! craniocervical region   [DEF: "The anteriormost subdivision of the body that includes the head, jaws, pharyngeal region and the neck (if present). In vertebrates this is the subdivision that includes the cervical vertebrae."]
  - [UBERON:0000033](http://purl.obolibrary.org/obo/UBERON_0000033) ! head [DEF: "The head is the anterior-most division of the body [GO]."]
  - [UBERON:0000974](http://purl.obolibrary.org/obo/UBERON_0000974) ! neck [DEF: "Subdivision of body proper, which consists of a maximal set of diverse subclasses of organ and organ part spatially associated with the cervical vertebral coumn, it is partially surrounded by skin of neck. Examples: There is only one neck[FMA]."]

Should ZFA head be mapped to this parent class?

For now, only consider vertebrates - let's not get into the insect head problem...

Note: objections have been raised in the past about the term "craniocervical region". But I think we need some kind of logical structure like this regardless of what we call it.

One option is to call the parent "head" and the child "tetrapod head", but this is ugly, and would make the ontology confusing for mammalian users who expect the head to be... the head.

**Comment by gouttegd** [comment] 2021-08-03 09:44
WARNING: This issue has been automatically closed because it has not been updated in more than 3 years. Please re-open it if you still need this to be addressed addressed addressed – we are now getting some resources to deal with such issues.

**Comment by gouttegd** [comment] 2024-09-04 16:31
Reopening as part of an effort (for Ubergraph, cf https://github.com/INCATools/ubergraph/pull/143) towards fixing the incompatibilities between ZFA and Uberon.

Of all the unsats in the merge of Uberon + ZFA, about 80 are caused by the disagreement explained in this ticket about what is a “head“ in ZFA and in Uberon.

They could all be resolved by a two-parts fix:

The first part, already evoked in the ticket, is simply to remap '[ZFA:head](http://purl.obolibrary.org/obo/ZFA_0001114)' to '[UBERON:craniocervical region](http://purl.obolibrary.org/obo/UBERON_0007811)' (instead of '[UBERON:head](http://purl.obolibrary.org/obo/UBERON_0000033)'), which is consistent with what ZFA calls a “head”.

The second part is to remove the following axiom in Uberon:

> '[pharyngeal arch](http://purl.obolibrary.org/obo/UBERON_0002539)' [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some '[embryonic head](http://purl.obolibrary.org/obo/UBERON_0008816)'

'[embryonic head](http://purl.obolibrary.org/obo/UBERON_0008816)' is defined relatively to its non-embryonic counterpart, which refers strictly to the head and excludes the cervical region. As a result, this axiom causes all the “post-hyoid pharyngeal arches” in ZFA (and their multiple derived structures) to be unsatisfiable.

If we don’t want to entirely lose that axiom, we could replace it with

> '[pharyngeal arch](http://purl.obolibrary.org/obo/UBERON_0002539)' [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some 'embryonic craniocervical region'

where 'embryonic craniocervical region' would be a new term defined as the embryonic counterpart to '[craniocervical region](http://purl.obolibrary.org/obo/UBERON_0007811)'.

**Closed** 2024-10-25 09:10 UTC
Labels: mapping
