### ISSUE TITLE
invalid owl expressions being brought in to composite-metazoa

### ISSUE THREAD

**Issue by cmungall** [obophenotype/uberon#1958] opened 2021-07-06 19:45 UTC
```
$ obo-grep.pl  -r 'is_a: Error' composite-metazoan.obo  | grepcid
137
```

e.g.

```
[Term]
id: ZFA:0007125
name: midbrain hindbrain boundary constriction (Danio)
def: "A portion of tissue that is the deepest point of the fold of the midbrain hindbrain boundary. In zebrafish the midbrain hindbrain boundary constriction (MHBC) is formed soon after neural tube closure. The MHBC is formed by the bending of the basal side of the neuroepithelium." [GOC:ymb, ORCiD:0000-0002-9900-7880, ZFIN:ZDB-PUB-080825-24]
synonym: "MHBC" EXACT [ZFIN:ZDB-PUB-080825-24]
is_a: Error2
is_a: UBERON:0000479 ! tissue
is_a: UBERON:0004121 ! ectoderm-derived structure
relationship: existence_ends_during_or_before ZFS:0000044 ! Adult
relationship: existence_starts_during_or_after ZFS:0000026 ! Segmentation:14-19 somites
relationship: part_of UBERON:0003052 ! midbrain-hindbrain boundary
```

in cm.owl:

```xml
    <!-- http://purl.obolibrary.org/obo/ZFA_0007125 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/ZFA_0007125">
        <rdfs:subClassOf rdf:resource="http://org.semanticweb.owlapi/error#Error2"/>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000479"/>
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/UBERON_0004121"/>
        <rdfs:subClassOf>
```

I am not sure where these are introduced.

I suggest as a first pass filtering these

See also https://github.com/ontodev/robot/issues/878

**Comment by cmungall** [comment] 2021-07-06 19:49
note these are not present in the last release

**Comment by cmungall** [comment] 2021-07-06 19:52
here is a comparison with EHDAA2 (which never changes)

old:

```
id: EHDAA2:0000800
name: hypopharyngeal eminence associated mesenchyme (human)
is_a: AEO:0000146 ! dense mesenchyme tissue
is_a: UBERON:0000077 ! mixed endoderm/mesoderm-derived structure
is_a: UBERON:0010314 ! structure with developmental contribution from neural crest
relationship: develops_from UBERON:0005690 ! 3rd arch mesenchyme
relationship: develops_from UBERON:0005691 ! 4th arch mesenchyme
relationship: existence_ends_during_or_before HsapDv:0000025 ! CS18
relationship: existence_starts_during_or_after HsapDv:0000020 ! Carnegie stage 13 (human)
relationship: part_of UBERON:0010057 ! hypopharyngeal eminence
```

new:

```
id: EHDAA2:0000800
name: hypopharyngeal eminence associated mesenchyme (human)
is_a: AEO:0000146 ! dense mesenchyme tissue
is_a: Error2
is_a: UBERON:0000077 ! mixed endoderm/mesoderm-derived structure
is_a: UBERON:0010314 ! structure with developmental contribution from neural crest
relationship: develops_from UBERON:0005690 ! 3rd arch mesenchyme
relationship: develops_from UBERON:0005691 ! 4th arch mesenchyme
relationship: existence_ends_during_or_before HsapDv:0000025 ! CS18
relationship: existence_starts_during_or_after HsapDv:0000020 ! Carnegie stage 13
relationship: part_of UBERON:0010057 ! hypopharyngeal eminence

```

**Comment by gouttegd** [comment] 2023-11-16 11:18
> I am not sure where these are introduced.

They come from `src/ontology/imports/local-poro.owl`, our local copy of the Porifera ontology (PORO). It contains the following general class axioms:

> (BFO:0000050 some UBERON:0000466) SubClassOf: <http://org.semanticweb.owlapi/error#Error2>
> (BFO:0000050 some UBERON:0001062) SubClassOf: <http://org.semanticweb.owlapi/error#Error1>

This was fixed in upstream PORO in [November 2021](https://github.com/obophenotype/porifera-ontology/commit/2d6c60c8d9d85c84252f695605f466d87b71ddee) but our local copy (as all the other `local-*.owl` copies) has been frozen since September 2021, so we never got the fix.

I just tested removing the offending axioms from our local copy and I can confirm this gets rid of all occurrences of `<http://org.semanticweb.owlapi/error#Error1>` and `<http://org.semanticweb.owlapi/error#Error2>` in composite-metazoan.

**Closed** 2023-11-17 16:35 UTC
Labels: composite
