### ISSUE TITLE
Review the need of expand-dbxref-literals.pl

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#2974] opened 2023-07-15 15:57 UTC
Moved from https://github.com/obophenotype/uberon/issues/2967#issuecomment-1631312311

@gouttegd 

1. inquires of the initial intention of the `expand-dbxref-literals.pl` script and
2. notes that it has not been working for many months (and releases) and
3. wonders if it provides the desired behaviour.

Script: 

https://github.com/obophenotype/uberon/blob/master/src/scripts/expand-dbxref-literals.pl

This is where it is used: https://github.com/obophenotype/uberon/blob/master/src/ontology/uberon.Makefile#L113

@cmungall looking at this script, without a great understanding of the surrounding pipeline: I tend to agree with @gouttegd that it does not exactly serve any modern purpose. Unless the IRI expansions are somehow needed later for generating owl axioms (in the composite files?)?

**Comment by matentzn** [comment] 2023-07-15 15:58
@gouttegd also said:

> And by the way, if/when someones does ask for CURIE expansion to be restored, they can use that opportunity to state clearly what should be expanded and where, exactly.

> The current script, back when it worked, only expanded CURIEs in oboInOwl:source and oboInOwl:hasDbXref annotations and only expanded a handful of prefixes. Was there a reason for that? Were the other prefixes left unexpanded on purpose? Should we stick to expand only those prefixes in those annotations? All things I’d very much like to know before I do anything.

**Comment by gouttegd** [comment] 2023-07-15 17:10
Of note, this is not the first time CURIE expansion has been broken without anybody noticing: https://github.com/obophenotype/uberon/issues/2145

**Comment by gouttegd** [comment] 2023-07-15 17:33
Of note (bis), if it is decided that CURIE expansion _is_ desired:

An example of how we could perform CURIE expansion with a few lines of Java code in a ROBOT plugin (avoiding both the time-consuming step of dumping the ontology into a file just to process the file by a Perl script between two ROBOT commands, and the risk of the entire process being broken by the next change in the serialisation format): https://github.com/gouttegd/uberon-robot-plugin/commit/77425e4435435a47b04c2a4e68a6d2c7bc7cf943

```sh
$(OWLSRC): $(SRC) $(COMPONENTSDIR)/disjoint_union_over.ofn
        $(ROBOT) merge -i $< \
                       -i $(COMPONENTSDIR)/disjoint_union_over.ofn \
                       -i issues/contributor.owl \
                 uberon:expand-curies -a oboInOwl:source -a oboInOwl:hasDbXref \
                                      --prefix 'pmid: https://www.ncbi.nlm.nih.gov/pubmed/' \
                                      --prefix 'Wikipedia: http://en.wikipedia.org/wiki/' \
                                      --prefix 'doi: https://doi.org/' \
                                      [… other prefixes as needed …] \
                 expand --no-expand-term http://purl.obolibrary.org/RO_0002175 \
			-o $@
```

**Comment by matentzn** [comment] 2023-07-15 17:40
Awesome!

**Comment by gouttegd** [comment] 2023-07-16 14:27
Of note (ter), the `expand-dbxref-literals.pl` may have another problem beyond the fact that the regex it uses to find the annotation to expand no longer works since OWL API 4.5.25.

The script finds a line like the following:

```xml
  <oboInOwl:hasDbXref>UMLS:C0206417</oboInOwl:hasDbXref>
```

(I’ve left aside the `rdf:datatype...` for clarity; they are not what matters here) and transforms it into the following:

```xml
  <oboInOwl:hasDbXref rdf:resource="http://linkedlifedata.com/resource/umls/id/C0206417"/>
```

So far, so good?

Except if… the `oboInOwl:hasDbXref` annotation assertion axiom is _itself_ annotated, as it precisely is a few lines further down:

```xml
  <owl:Axiom>
    <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000010"/>
    <owl:annotatedProperty rdf:resource="http://www.geneontology.org/formats/oboInOwl#hasDbXref"/>
    <owl:annotatedTarget>UMLS:C0206417</owl:annotatedTarget>
    <oboInOwl:source>BIRNLEX:1111</oboInOwl:source>
  </owl:Axiom>
```

That part of the file is left unmodified by the `expand-dbxref-literals.pl` script, meaning the _annotatedTarget_ part of the axiom annotation, which has _not_ been expanded, no longer match the value of the (expanded) annotation assertion axiom. As a result, this `<owl:Axiom>` node is now interpreted as being an annotation on a completely different axiom.

The end result may be easier to comprehend in functional syntax. Before CURIE expansion:

```
AnnotationAssertion(
  Annotation(oboInOwl:source "BIRNLEX:1111")
  oboInOwl:hasDbXref UBERON:0000010> "UMLS:C0206417"
)
```

After CURIE expansion:

```
AnnotationAssertion(oboInOwl:hasDbXref UBERON:0000010 <http://linkedlifedata.com/resource/umls/id/C0206417)
AnnotationAssertion(
  Annotation(oboInOwl:source "BIRNLEX:1111")
  oboInOwl:hasDbXref UBERON:0000010 "UMLS:C0206417"
)
```

We end up with _two_ annotations on `UBERON:0000010`: the “real” one whose CURIE value has been expanded, but which has lost its own annotation in the process, and the one inferred by the presence of the `<owl:Axiom>` node, which has kept its annotation but has been left unexpanded.

Now, it could be argued that having both an expanded version of the annotation and an unexpanded one is actually a _feature_, not a bug. But it sure looks like a bug to me, so if it _is_ the desired behaviour, I’d like that to be explicitly clarified.

**Comment by matentzn** [comment] 2023-07-16 15:44
Seems like a bug to me, yet another reason to consider dropping this

**Comment by cmungall** [comment] 2023-07-17 14:54
You can drop support. It definitely is not needed for composite. This was
simply an early attempt to retain editing in obo yet produce more rdf/owl
friendly release files. Supplanted by newer methods.

**Comment by gouttegd** [comment] 2023-07-19 18:51
Closing since we have our answer.

**Closed by gouttegd** 2023-07-19 18:51 UTC
