### ISSUE TITLE
import UBERON into BFO based ontology

### ISSUE THREAD

**Issue by wdduncan** [obophenotype/uberon#1220] opened 2016-06-03 18:52 UTC
I am trying to use UBERON for an ontology of GYN cancers. My import of UBERON, however, is not aligned with BFO in the sense that UBERON:material anatomical entity is not a subtype of BFO:material entity and UBERON:immaterial anatomical entity is not a subtype of BFO:immaterial anatomical entity. 

When I add axioms to align the UBERON and BFO types, UBERON becomes inconsistent (using ELK reasoner). This presents me with interesting choices:
1. Leave the UBERON hierarchy under the class Thing.
2. Try to fix the UBERON axioms/classes so that some basic assertions (such as material and immaterial entities are disjoint) can be reasoned over.

Has anyone else dealt with this?

Thanks,
Bill

**Comment by cmungall** [comment] 2016-06-03 21:29
I'm updating the build process to include bridging axioms to BFO then run everything through the test suite. You shouldn't need to make any changes, provided you can wait til the next release, probably next week

**Comment by cmungall** [comment] 2016-06-03 21:57
Hmm travis still shows build passing, need to investigate further...

can I confirm the exact combination of purls you are combining?

**Comment by cmungall** [comment] 2016-06-04 01:29
Latest on this: a few releases ago we noticed that combing RO with Uberon resulted in Elk hanging. This was resolved by reverting to a previous RO. This is possibly the reason for the difference in our results.

The RO issue will be hard to resolve, there is no axiom that is obviously problematic, and if Elk hangs it makes it very hard to debug the ontology...

**Comment by wdduncan** [comment] 2016-06-06 13:35
The PURL I've been using for UBERON is http://purl.obolibrary.org/obo/uberon.owl. The ontology version IRI is http://purl.obolibrary.org/obo/uberon/releases/2016-05-11/uberon.owl.

I tried building UBERON myself from the git repos. But, I can't seem to get it working correctly. Is there a document that explains how to do this and what libraries you need?

**Comment by cmungall** [comment] 2016-06-06 14:42
I can provide docs if you really need to do that, but I suspect you don't. Uberon has a very particular and complex development cycle... the PURLs should be fine.

Would you be able to post a screenshot of the explanation of the unsatisfiability? I'm still having trouble reproducing.

**Comment by cmungall** [comment] 2016-06-06 14:43
Also if you can post the ELk version too

**Comment by wdduncan** [comment] 2016-06-06 15:14
The version of ELk is 0.4.3. The version of Protege is 5-RC-1.

The attached screenshots are:

1. my addition of an subclass axiom showing that an immaterial anatomical
entity is a subclass of immaterial entity
2 my addition of an subclass axiom showing that a material anatomical
entity is a subclass of material entity
3. the resulting inconsistent classes
4. the explanation given for why the class nose is inconsistent

I've also attached the MIREOT of UBERON (as a zip file) that I am using.

Bill
<img width="881" alt="screen shot 2016-06-06 at 11 02 09 am" src="https://cloud.githubusercontent.com/assets/3186638/15826978/aeb3e18a-2bd7-11e6-8b35-f145a4a287dc.png">
<img width="1459" alt="screen shot 2016-06-06 at 11 05 40 am" src="https://cloud.githubusercontent.com/assets/3186638/15826979/aeb7e280-2bd7-11e6-9494-911a247137dc.png">
<img width="547" alt="screen shot 2016-06-06 at 11 03 42 am" src="https://cloud.githubusercontent.com/assets/3186638/15826981/aebbeea2-2bd7-11e6-8731-7197d792fe74.png">
<img width="836" alt="screen shot 2016-06-06 at 11 02 31 am" src="https://cloud.githubusercontent.com/assets/3186638/15826980/aeba52ae-2bd7-11e6-9ae8-92920ea5c141.png">

[uberon-import-20160603.owl.zip](https://github.com/obophenotype/uberon/files/300697/uberon-import-20160603.owl.zip)

**Comment by cmungall** [comment] 2016-06-06 15:30
Thanks!

**Comment by gouttegd** [comment] 2021-08-03 10:23
WARNING: This issue has been automatically closed because it has not been updated in more than 3 years. Please re-open it if you still need this to be addressed addressed addressed – we are now getting some resources to deal with such issues.

**Closed by gouttegd** 2021-08-03 10:23 UTC
Labels: autoclosed-unfixed
